### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Iamtheoldman** [OpaceDigitalAgency/ai-scribe-chat-gpt-content-creator#1]
Wordpress updated today and when we went to find the amazing plugin it was deleted

**Comment by OpaceDigitalAgency** [comment]
Hi @Iamtheoldman, can you please confirm if this is still the case? It's definitely there - [https://wordpress.org/plugins/ai-scribe-the-chatgpt-powered-seo-content-creation-wizard/](https://wordpress.org/plugins/ai-scribe-the-chatgpt-powered-seo-content-creation-wizard/ )

**Comment by OpaceDigitalAgency** [comment]
I'll close for now, but please let us know if you have any issues.
